name: hello-world
on: push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code 
        uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
        
