name: hello-world
on: push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code 
        uses: actions/checkout@v3
      - run: echo '$(cat hello_world.txt)'
